### ISSUE TITLE
Problem with parse_ini_file() changes

### ISSUE THREAD

**Issue by Sobak** [Sobak/php7-migration-guide#7]
Hello guys!

We do have a little problem with changes made to `parse_ini_file()` and `parse_ini_string()` functions. New `INI_SCANNER_TYPED` mode was added in PHP 5.6.1. I'll skip my bashing on that decision, as it doesn't change anything, but the problem is that this is widely recognized as PHP7 feature. 

Even you, @salathe, have listed it on go-php7-docs todo list, and you, @tpunt in your PHP7 Reference. This choice is rather logical because it's hard to make a migration guide for a point version, but practically, this change doesn't belong to PHP7.

What are your thoughts on that? Should we document it here, mention that in fact this is PHP 5.6.1 feature and try not to cry?

Cheers,
Sobak.

**Comment by salathe** [comment]
`INI_SCANNER_TYPED` should not go in to the PHP 7 migration guide.

 It should be documented as any other change in the appropriate places: it's already mentioned under parse_ini_file/string() but needs to be added to http://php.net/manual/en/filesystem.constants.php and the ChangeLog-5.php list at least.

**Comment by tpunt** [comment]
I agree that it should not go in the PHP 7 migration guide. Otherwise, other constants introduced in minor versions (like `MYSQL_ATTR_MULTI_STATEMENTS`) would need to be put in there too.

Also, I don't remember writing about that in the PHP 7 reference (an accidental miss, probably :)).
