### ISSUE TITLE
Time to move the migration guide to the manual? 

### ISSUE THREAD

**Issue by cmb69** [Sobak/php7-migration-guide#9]
PHP 7.0.0beta3 is supposed to be released tomorrow, and people are already testing, and they're facing unexpected changes which they report as bugs (see, for instance, [#70200](https://bugs.php.net/bug.php?id=70200) and [#70201](https://bugs.php.net/bug.php?id=70201)). Handling these bug reports is additional work, and we can't even tell the reporters to RTFM, because it's missing.

IMO we should move the migration guide to php.net as soon as possible, even if it is still work in progress.

**Comment by Sobak** [comment]
I think @tpunt made all planned structural changes and if so, I'm ready to commit it tomorrow.

**Comment by tpunt** [comment]
I think a few more structural changes may be needed:
- A new "Changes to INI File Handling" section
- A new "Other Changes" section (for generic changes, like div/0)
- A new "Removed Extensions and SAPIs" section (unless we want to bundle that content in with "Changes in SAPI modules" and "Other Changes to Extensions"

I'll add in the first two sections now - I'm not sure whether to dedicate a new section for all the removed sapis/exts or not. @Sobak @salathe

**Comment by salathe** [comment]
> IMO we should move the migration guide to php.net as soon as possible, even if it is still work in progress.

Absolutely my feeling too.

>  I'm not sure whether to dedicate a new section for all the removed sapis/exts or not.

I think a separate section for removed exts is a worthwhile choice.

>  I'm ready to commit it tomorrow.

Fantastic. Looking forward to it.

**Comment by tpunt** [comment]
I'll add in that section now to my PR

**Comment by Sobak** [comment]
It has just been commited to svn.php.net, see http://svn.php.net/viewvc?view=revision&revision=337323

Just wait a few hours and it should became available on docs.php.net and tomorrow on all other mirrors.

Thank you all, guys, for the cooperation!

**Comment by cmb69** [comment]
Thanks, Maciej!

> Just wait a few hours and it should became available on docs.php.net […]

Most likely not, see https://bugs.php.net/bug.php?id=70203. :(

**Comment by Sobak** [comment]
@cmb69 hmm, that's worrying or at least inconvenient, but in this case, we just need to wait till tomorrow, I guess.
